### ISSUE TITLE
Search Options

### ISSUE THREAD

**Issue by htarver** [unt-libraries/django-name#113]
The search box always defaults to "Personal" names in the drop-down menu.

Ideally, it would be nice to have the default be unlimited, i.e., search across all names or for any kind of name.

**Comment by somexpert** [comment]
On top of the search defaulting to an unlimited search, it is clear from within the code that after a search is performed, the search option should be remembered for subsequent searches. This is not the case. Might as well kill two birds with one stone here. (no birds will actually be harmed)

**Comment by htarver** [comment]
Oh, Yay. It has also bothered me that if I choose a type up front, the search doesn't default to that type; but if the default is "any" it wouldn't matter.

Sent from my iPhone
