### ISSUE TITLE
create export.json for all names

### ISSUE THREAD

**Issue by vphill** [unt-libraries/django-name#131]
So that we can better incorporate the names in the name system into our other infrastructure it would be useful to have an output from the system that is in the format we are using in edit for other external vocabularies. 

Currently we have an /export/ URL that returns a tsv file

```
personal	Abeysinghe, I. Sarath B.	http://digital2.library.unt.edu/name/nm0003905/
personal	Abian, Maria	http://digital2.library.unt.edu/name/nm0010453/
```

I think we could have an export.json file in the following format. 

```json
[
  {
    "i": "nm0003905",
    "l": "http://digital2.library.unt.edu/name/nm0003905/",
    "t": "Abeysinghe, I. Sarath B."
  },
  {
    "i": "nm0010453",
    "l": "http://digital2.library.unt.edu/name/nm0010453/",
    "t": "Abian, Maria"
  }
]

```

**Comment by somexpert** [comment]
so without the type info?
