### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/django-name#14]
Lets get some continuous integration setup once the tests are in a better condition, because that is a good thing to do. I am thinking TravisCI.

**Comment by ldko** [comment]
Joey set up an instance of Jenkins at one point.

**Comment by damonkelley** [comment]
Good to know @ldko. 

I was thinking of using Travis because is deeply integrated with Github. Here is an example of a pull request on a project that uses Travis. https://github.com/tomchristie/django-rest-framework/pull/2769
