### ISSUE TITLE
Refactor the Merge Validator

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/django-name#22]
`validate_merged_with()` is the custom validator to determines whether or not one Name can be merged with another. The current implementation is a bit confusing, because validation passes if _any_ exception is thrown. 

We may also want to get the `to_be_merged` variable by looking up the Name object by id, instead of creating the `name_id` manually through string interpolation. This will decouple the validator from the implementation details of the name_id.

This is the current implementation.

``` python
def validate_merged_with(value):
    """
    Custom validator for the merged with CharField.
    We don't want to allow users to do an infinite redirect loop b/c of
    merging a record that is already merged with the current record
    """

    try:
        # attempt to set the variables to their values
        to_be_merged = 'nm%07d' % value
        current = str(Name.objects.get(name_id=to_be_merged).merged_with)
        current_merged = str(Name.objects.get(name_id=current).merged_with)
    except Exception:
        # make the comparison variables different to ensure test failure
        current_merged = '1'
        to_be_merged = '2'

    # test if they are looped
    if current_merged == to_be_merged:
        raise ValidationError(
            u'can\'t merge a record into an infinite redirect loop'
        )
```

**Comment by ldko** [comment]
Yes, I agree that the exception handling is too broad. Also, as you say, replacing 'nm%07d' % value to allow non-'nm'-starting identifiers would be good.

**Comment by ldko** [comment]
Currently we can set merged to each other once and it works, but then records can't be saved again. Another problem is that we can still set merged as: 1 to 2, 2 to 3, 3 to 1 and get infinite loops for all of them.
