### ISSUE TITLE
Stats View Should Not Return 500

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/django-name#23]
Currently if there are no Names in the database, the `stats` view will throw a 500. We should handle this scenario more gracefully. Perhaps the page should still render, but a message stating that there are no stats currently available.

**Comment by vphill** [comment]
I like the "page should still render" as expected. with a message stating that there are no stats currently available.

**Comment by damonkelley** [comment]
Lets revisit this after the javascript and template changes have been made. That would be after #4 and #7. The problem is that the exception is being thrown in one of the stats utility methods, and it will be easier to fix this once I have a better idea of what the data is being fed into.

**Comment by damonkelley** [comment]
#47 takes care of this one.

**Comment by damonkelley** [comment]
Closed via #45
