### ISSUE TITLE
Fix the Map Page

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/django-name#25]
The map page appears to be broken. I don't think it has anything to do with code, but rather the service we are integrating with.

Currently, we are setup to use [CloudMade](http://cloudmade.com/solutions/portals), but it looks like there platform has evolved since this app was first developed.

Check and see if we still have a CloudMade account, and if they still offer a free tier. If not, I am thinking we should reimplement the map section directly using the Google Maps API.

**Comment by vphill** [comment]
If we can let's try and stick with leaflet for the maps.  I don't know what CloudMate is actually doing,  maybe simplifying the setup or providing the tiles?

**Comment by damonkelley** [comment]
This is definitely due to the tiles no longer being available. Once I replaced to call to CloudMade with the OpenStreetMap url, the map was displaying. 

Another issue with this is that if there are no names, the JS for rendering the map with throw and exception. We should fix that.

**Comment by damonkelley** [comment]
Closed via #38
