### ISSUE TITLE
Misleading record counts on landing page

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-name#28]
Currently record counts given on the landing page include suppressed and deleted records.

**Comment by damonkelley** [comment]
I think I have gotten to the bottom of this. It appears that perhaps at one point the number of deleted and suppressed Names were also displayed on the landing page, which would make sense that the total number of names include deleted and suppressed. 

@ldko @vphill,
Should we keep the current implementation and add the deleted and suppressed counts? Or should we update the way we are calculating the total number of Names? 

I am fine with either one, and both options are relatively simple to implement.

**Comment by ldko** [comment]
@damonkelley @vphill,
I am not exactly sure what the general use of the "suppressed" status is. To me it doesn't make sense to include "deleted" records, and I would say not to count "suppressed" on that page either, but not knowing when we use "suppressed", it might be good for Mark to chime in.

**Comment by damonkelley** [comment]
@ldko 

I totally get that and agree. I wasn't sure if "suppressed" and "deleted" were useful statistics for the domain that this app fits into.

**Comment by vphill** [comment]
On the front page we want to display just "active" records and ignore the suppressed and deleted records in any counts that we put there.

**Comment by ldko** [comment]
Should we also ignore records that have "merged_with_id" that is not null in record counts?

**Comment by damonkelley** [comment]
That is a good question @ldko. I suppose it depends on if merged records _should_ or _should not_ be active. Currently, you can merge a record and leave it active. 

What do you think @vphill?

**Comment by ldko** [comment]
It is my understanding from talking to Laura and looking at the records in the production database, that currently when records are merged_with another, they are left with the "active" status.

**Comment by vphill** [comment]
I think we should ignore merged records in the stats,  if a record is marked as merged and has a merged with identifier, the record marked as merged should stay active and the app will just forward the request to the correct record. 

For counts we can ignore merged records though.

**Comment by damonkelley** [comment]
I agree that merged names should not be present with the Count statistics (both on the landing pages, and on the stats page), but the Created and Modified Name stats should include **all** names.

It seems to make more sense to me since we are just counting the number of created and modified for a given month.

**Comment by vphill** [comment]
I wasn't thinking about Created and Modified Names for stats. 

I agree with you that Created and Modified Name stats should include **all** names

**Comment by damonkelley** [comment]
Cool, I think that settles it then. 

As of #47, there are new manager methods for the `Name` model. The `visible()` method is what all views are using to provide an initial queryset, that may or may not be further filtered upon. That method only retrieves the Active and non-merged Names. You can see it [here](https://github.com/unt-libraries/django-name/blob/3f60e4ba80a8564b9aea9b91b0939acd6d0dd119/name/models.py#L294-L299). 

Now that this is contained to one method, it should significantly reduce the number of inconsistencies across views.

@ldko, do you have anything to add?

**Comment by ldko** [comment]
No.

**Comment by damonkelley** [comment]
Just went through to verify if there are any places that were overlooked. 

This [line](https://github.com/unt-libraries/django-name/blob/master/name/views.py#L157) should retrieve the `visible()` queryset before calling `count()`
