### ISSUE TITLE
changes for /name/feed

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-name#42]
1. To be compliant with the Atom Syndication Format /name/feed/ Atom Feed should have author field at least at feed level.
2. For `<link>` in `<entry>`, if there is a port for the site, it is not being given in the link. For example, if I am serving this site at http://localhost:8000, the link shows without the ":8000":

```
<entry>
  <title>Willis Library</title>
  <link href="http://localhost/name/nm0000007/" rel="alternate"></link>
  <id>http://localhost/name/nm0000007/</id>
  <summary type="html">Name Type: Building</summary>
</entry>
```
1. In production right now, the Content-Type returned is application/xml and it handles pretty printing in Chrome. Here it is Content-Type: application/atom+xml; charset=utf-8 (which makes sense to me) but  it is not actually pretty printing in Chrome as mentioned at the dev meeting yesterday by @vphill.

**Comment by damonkelley** [comment]
Also, right now the `VOCAB_DOMAIN` is being used to create the links in the feed. This is left over from the previous iteration.

Do we want to encourage users to define there own `VOCAB_DOMAIN` in their project settings and pick that up in the app? Or do we just use the URL to the name detail page?

If so, we could default to using `item.get_absolute_url()` if the `VOCAB_DOMAIN` setting is `None`

**Comment by ldko** [comment]
I believe the ids and the links in the feed entries should just be the actual URL to the name detail page. I don't know why it is using VOCAB_DOMAIN there.

**Comment by vphill** [comment]
I agree with @ldko and the suggestion to just use item.get_absolute_url()

**Comment by ldko** [comment]
I talked to @vphill, and he does want us to explicitly set the mimetype for the feed page response to application/xml.
