### ISSUE TITLE
ItemType Encapsulation

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/django-name#96]
The the structured data on the name detail page currently consists of 

``` html
<div itemscope itemtype="http://schema.org/Person">
    <h2 class="named">Last Name, First Name</h2>
</div>
```

We need to change this so that the closing `<div>` of the itemscope  encapsulates all of the structured data elements.

**Comment by vphill** [comment]
Just an fyi,  I think this applies to all "types" including Organization, Software and Building,  basically just that itemscope div needs to go at the end of the statements about the item.
